name: vib-ribbon (Europe)
options:
    # paths
    basename:    vib-ribbon
    base_path:   ..
    target_path: iso/MAIN_T.EXE
    asm_path:    asm/game/
    asset_path:  assets/
    src_path:    src/game/
    
    # compiler
    platform:    psx
    compiler:    GCC
    
    # disasm
    symbol_addrs_path:           config/symbols.sces028.txt
    undefined_funcs_auto_path:   config/undefined_funcs_auto.sces028.vib-ribbon.txt
    undefined_syms_auto_path:    config/undefined_syms_auto.sces028.vib-ribbon.txt
    find_file_boundaries:        yes
    use_legacy_include_asm:      no
    migrate_rodata_to_functions: no
    disasm_unknown:              yes
segments:
    - [0, header]
    - name:  vib-ribbon
      type:  code
      start: 0x00000800
      vram:  0x80019000
      subalign: 4
      subsegments:
        - [0x800, rodata] # rodata
        - [0x4D58, c]     # text
        - [0x13778, asm, entrypoint]
        - [0x13868, c, psyq]
        - [0x27118, data] # data
        - [0x2F6C0, data] # sdata
        - [0x2F964, data] # sbss
        - [0x2F970, data] # bss
        #- [0x2F92C, data] # bss
    - [0x30000]